### ISSUE TITLE
Full support for Authentik as SSO-Provider

### ISSUE THREAD

**Issue by samuel-p** [eikek/sharry#1009]
I tried to add Authentik as Provider in the OAuth config, but did not get it to work. Like on #889 I got the same errors and want to share my information in more detail.

First to clarify, Authentik has two options (path styles) to use for authentication:

1. OAuth2 Provider (This provider supports both generic OAuth2 as well as OpenID Connect)
   Endpoint | URL
   -- | --
   Authorization | /application/o/authorize/
   Token | /application/o/token/
   User Info | /application/o/userinfo/
   Token Revoke | /application/o/revoke/
   End Session | /application/o/my-app/end-session/
   JWKS | /application/o/my-app/jwks/
   OpenID Configuration | /application/o/my-app/.well-known/openid-configuration
2. GitHub Compatibility (This provider also exposes a GitHub-compatible endpoint. This endpoint can be used by applications, which support authenticating against GitHub Enterprise, but not generic OpenID Connect.)
   Endpoint | URL
   -- | --
   Authorization | /login/oauth/authorize
   Token | /login/oauth/access_token
   User Info | /user
   User Teams Info | /user/teams

Unfortunately none of them worked.

If I use the generic OAuth2 Provider my config looks like this:

```
sharry.restserver {
  backend {
    auth {
      oauth = [
        {
          enabled = true
          id = "authentik"
          name = "Authentik"
          icon = "fas fa-user"
          authorize-url = "https://my.authentik.domain/application/o/authorize/"
          token-url = "https://my.authentik.domain/application/o/token/"
          user-url = "https://my.authentik.domain/application/o/userinfo/"
          user-id-key = "sub"
          user-email-key = "email"
          client-id = "<client-id>"
          client-secret = "<client-secret>"
        }
      ]
    }
  }
}
```

In the Login-Process I get the following Logs:

```
share-sharry-1  | 2023.03.03 00:55:44:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/authentik
share-sharry-1  | 2023.03.03 00:55:44:0002 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 303 See Other
share-sharry-1  | 2023.03.03 00:55:46:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /sw.js
share-sharry-1  | 2023.03.03 00:55:46:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
share-sharry-1  | 2023.03.03 00:55:47:0000 [io-comp...] [ERROR] sharry.restserver.oauth.CodeFlow.codeToToken:76 - Error obtaining access token '301' / IO(...)
share-sharry-1  | 2023.03.03 00:55:47:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/authentik/resume?code=<code>&state=
share-sharry-1  | 2023.03.03 00:55:47:0002 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 307 Temporary Redirect
share-sharry-1  | 2023.03.03 00:55:47:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /app/login?oauth=1
share-sharry-1  | 2023.03.03 00:55:47:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
share-sharry-1  | 2023.03.03 00:55:47:0003 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/info/version
share-sharry-1  | 2023.03.03 00:55:47:0004 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
share-sharry-1  | 2023.03.03 00:55:48:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /api/v2/sec/auth/session
share-sharry-1  | 2023.03.03 00:55:48:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
```

So I get the following error every time when I try to login:

> There was an invalid response status: 403

If I use the GitHub Compatibility _Mode_ my config looks like this:

```
sharry.restserver {
  backend {
    auth {
      oauth = [
        {
          enabled = true
          id = "authentik"
          name = "Authentik"
          icon = "fas fa-user"
          authorize-url = "https://my.authentik.domain/login/oauth/authorize"
          token-url = "https://my.authentik.domain/login/oauth/access_token"
          user-url = "https://my.authentik.domain/user"
          user-id-key = "login"
          client-id = "<client-id>"
          client-secret = "<client-secret>"
        }
      ]
    }
  }
}
```

In the Login-Process I get the following Logs:

```
share-sharry-1  | 2023.03.03 01:14:10:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/authentik
share-sharry-1  | 2023.03.03 01:14:10:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 303 See Other
share-sharry-1  | 2023.03.03 01:14:12:0000 [io-comp...] [INFO ] sharry.restserver.oauth.CodeFlow.codeToToken:73 - Got token: Some(<token>)
share-sharry-1  | 2023.03.03 01:14:12:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v2/open/auth/oauth/authentik/resume?code=<code>&state=
share-sharry-1  | 2023.03.03 01:14:12:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - service raised an error: class org.http4s.MalformedMessageBodyFailure
share-sharry-1  | 2023.03.03 01:14:12:0002 [io-comp...] [ERROR] sharry.restserver.RestServer.applyOrElse:43 - Error processing request!
share-sharry-1  | org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON: empty body
share-sharry-1  | 	at org.http4s.jawn.JawnInstances$.defaultJawnEmptyBodyMessage(JawnInstances.scala:62)
share-sharry-1  | 	at org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage(JawnInstances.scala:35)
share-sharry-1  | 	at org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage$(JawnInstances.scala:34)
share-sharry-1  | 	at org.http4s.circe.package$.jawnEmptyBodyMessage(package.scala:19)
share-sharry-1  | 	at org.http4s.jawn.JawnInstances.$anonfun$jawnDecoderImpl$4(JawnInstances.scala:53)
share-sharry-1  | 	at scala.Option.getOrElse(Option.scala:201)
share-sharry-1  | 	at org.http4s.jawn.JawnInstances.$anonfun$jawnDecoderImpl$3(JawnInstances.scala:53)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at modify @ fs2.internal.Scope.close(Scope.scala:262)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
share-sharry-1  | 	at as @ sharry.restserver.Main$.$anonfun$run$17(Main.scala:70)
share-sharry-1  | 	at get @ fs2.internal.Scope.openScope(Scope.scala:281)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
share-sharry-1  | 	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
share-sharry-1  | 
```

So it results in the following error:

> Internal Error: Malformed message body: Invalid JSON: empty body

Maybe someone can dig into this or has an advice for me, what could be wrong in my config? I really like Sharry and would love to use it with my Authentik setup.

**Comment by eikek** [comment]
Thank you very much for the detailed report! I'll take a look, not sure when though. But your config looks good to me, it is probably some bug in sharry.

**Comment by eikek** [comment]
@samuel-p Actually the error message reminded me of something. I just pushed a fix to the url reader. I think authentik requires urls to end with a slash, otherwise it gives a redirect that sharry is not prepared for when processing the oauth response. I just tried it here successfully with the general oauth settings (I think using Authentik 2022.7.1). Once #1010 is merged and a snapshot version exists, you could try it out

**Comment by samuel-p** [comment]
Awesome, just tested it and it works now. Thank you very much for the quick bug fix!

Just a quick side note for others who might also come across this issue. Possible working values for `user-id-key` are

* `sub`
* `preferred_username`
* `email`

maybe others will work too. I ended up using `preferred_username` for better for better readability.

**Comment by eikek** [comment]
Nice, thanks for testing! Oh yes the values for `user-id-key` are not very obvious and depend on the provider and how it is setup. I'll do another change to allow specifying scopes from the config. This makes it then possible to add custom data to return from the IDP and pick it up from sharry.
