### ISSUE TITLE
How to fix database corruption ?

### ISSUE THREAD

**Issue by ybizeul** [eikek/sharry#1103]
When starting sharry, this happens:
```
07:16:56,714 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:16:56,837 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
07:16:56,904 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:16:56,938 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sharry] to DEBUG
07:16:56,938 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [emil] to DEBUG
07:16:56,938 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.http4s] to INFO
07:16:56,938 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
07:16:57,008 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
07:16:57,010 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
07:16:57,014 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@50b472aa - Registering current configuration as safe fallback point
2023-06-19 07:16:57,570 [main] INFO  s.r.Main - Using given config file: /opt/sharry.conf 
2023-06-19 07:17:05,213 [main] INFO  s.r.Main - 
***>   __ _
***>  / _\ |__   __ _ _ __ _ __ _   _
***>  \ \| '_ \ / _` | '__| '__| | | |
***>  _\ \ | | | (_| | |  | |  | |_| |
***>  \__/_| |_|\__,_|_|  |_|   \__, |
***>                            |___/
***>       v1.9.0 (#0e8cc113)
***>  Base-Url: https://upload.example.org
***>  Database: jdbc:h2:///data/h2.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
***>  Config:   /opt/sharry.conf
***>   
2023-06-19 07:17:05,220 [main] INFO  s.r.Main - Alias-Member feature enabled: true 
2023-06-19 07:17:14,433 [io-compute-0] INFO  s.s.m.FlywayMigrate - Running db migrations... 
2023-06-19 07:17:14,433 [io-compute-0] INFO  s.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/postgresql, classpath:db/migration/h2) 
Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:h2:///data/h2.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE) for user 'sa': General error: "java.lang.IllegalStateException: Chunk 5226 not found [1.4.200/9]" [50000-200]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 50000
Message    : General error: "java.lang.IllegalStateException: Chunk 5226 not found [1.4.200/9]" [50000-200]

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:66)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)
```

Not sure how to run a recovery, any pointers ?

**Comment by ybizeul** [comment]
Started from scratch as I didn't have anything important.

I tried the recovery procedure [here](http://www.h2database.com/html/advanced.html#using_recover_tool) without success.

**Comment by eikek** [comment]
Hi @ybizeul , I'm sorry i never had this error myself. Don't know what's the cause here. I think we would need to diagnose. Could it be that you updated sharry from some version before 1.9.0? I think H2 got updated in that release and prior database versions are not compatible.

**Comment by ybizeul** [comment]
The moment it happened I had sharry pinned to a specific release. I think somehow the database got corrupted and I had a global outage on that k8s cluster.
After that I tried upgrading without much success but error was constraint violation, and I’m under the impression that was because I didn’t log out/log in between tests but not sure. 
I’m a bit disappointed by the inability for H2 to recover though. I’ll go back to the doc but is there another backend available like SQLite ?

**Comment by eikek** [comment]
It seems things got really bad for h2. SQLite is not supported, but Postgres is which should do better in these scenarios than h2 and sqlite.
