### ISSUE TITLE
Database Error when starting nightly with postgres

### ISSUE THREAD

**Issue by samuel-p** [eikek/sharry#1263]
I run the nightly version since a few months, as I need a bug fix, which is not in a stable release for now. Since some versions I get the following Flyway error:

```
2023.12.06 00:15:17:964 io-compute-0 INFO sharry.restserver.Main.run:23
    Using given config file: /opt/sharry.conf    
2023.12.06 00:15:19:0000 [io-comp...] [INFO ] sharry.restserver.Main.run:54 - 
***>   __ _
***>  / _\ |__   __ _ _ __ _ __ _   _
***>  \ \| '_ \ / _` | '__| '__| | | |
***>  _\ \ | | | (_| | |  | |  | |_| |
***>  \__/_| |_|\__,_|_|  |_|   \__, |
***>                            |___/
***>       v1.13.0-SNAPSHOT (#c538d8d5)
***>  Base-Url: https://sharry.domain.com
***>  Database: jdbc:postgresql://database:5432/sharry
***>  Config:   /opt/sharry.conf
***>  FileRepo: FileSystem(true,/storage,true)
***>  
2023.12.06 00:15:19:0001 [io-comp...] [INFO ] sharry.restserver.Main.run:55 - 
Map(Ident(filesystem) -> FileSystem(true,/storage,true), Ident(minio) -> S3(enabled=false, endpoint=http://localhost:9000, bucket=sharry, accessKey=username, secretKey=***), Ident(database) -> DefaultDatabase(true))

2023.12.06 00:15:19:0002 [io-comp...] [INFO ] sharry.restserver.Main.run:62 - Alias-Member feature enabled: true
2023.12.06 00:15:19:0003 [io-comp...] [INFO ] sharry.store.migrate.FlywayMigrate.run:15 - Running db migrations...
2023.12.06 00:15:19:0004 [io-comp...] [INFO ] sharry.store.migrate.FlywayMigrate.makeFlyway:23 - Using migration locations: List(classpath:db/migration/postgresql)
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresql://database:5432/sharry
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1079)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:602)
	at sharry.store.migrate.FlywayMigrate$.makeFlyway(FlywayMigrate.scala:27)
	at sharry.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:16)
	at delay @ sharry.store.migrate.FlywayMigrate$.run(FlywayMigrate.scala:14)
	at map @ sharry.store.doobie.StoreImpl.migrate(StoreImpl.scala:16)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:161)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at get @ fs2.internal.Scope.openScope(Scope.scala:275)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1090)
	at >>$extension @ fs2.Pull$.fs2$Pull$$go$1(Pull.scala:1242)
	at get @ fs2.internal.Scope.openScope(Scope.scala:275)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:952)
	at get @ fs2.internal.Scope.openScope(Scope.scala:275)
```

I am running sharry in a docker compose setup with a postgres database. Looking through the issues I think this could be a regression of #766, but I am not 100% sure.

**Comment by eikek** [comment]
Thanks for reporting! You are right, it seems that flyway now requires another dependency again. This time for postgres, #766 it was for mariadb.
