### ISSUE TITLE
Email sending fails

### ISSUE THREAD

**Issue by maxanier** [eikek/sharry#20]
Hi,

I have issues with the email notification feature.
After trying to send an email notification the webinterfaces just displays an endless loading animation and the console prints the following error:

```
2017-10-14T20:15:08.807+0000 DEBUG [sharry-server-ACG-24] sharry.server.email.client [client.scala:44] Createt mime message: Date: Sat, 14 Oct 2017 20:15:08 +0000 (UTC)

From: <censored>

To: <censored>

Message-ID: <29182965.2.1508012108807@3d6622c3cbbd>

Subject: Ready to download

MIME-Version: 1.0

Content-Type: text/plain; charset=us-ascii

Content-Transfer-Encoding: 7bit

Hi,

I have pushed some files for you to download. Visit this page:

https://<censored>/#id=TuVK7_iESPYhC8xlH9f05I2dPawz1QAaq4
Cheers,
max
2017-10-14T20:15:09.642+0000 ERROR [sharry-server-ACG-24] sharry.server.email.client [client.scala:53] Error sending mail: Mail(List(To(Address(<censored>)), Subject(Ready to download)),Hi,

I have pushed some files for you to download. Visit this page:


Cheers,
max)
javax.mail.SendFailedException: Invalid Addresses
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at sharry.server.email.client$.$anonfun$send1$7(client.scala:50)
	at sharry.server.email.client$.$anonfun$send1$7$adapted(client.scala:50)
	at fs2.Task.$anonfun$map$3(Task.scala:47)
	at fs2.util.Attempt$.apply(Attempt.scala:12)
	at fs2.Task.$anonfun$map$2(Task.scala:47)
	at scala.util.Either.flatMap(Either.scala:269)
	at fs2.Task.$anonfun$map$1(Task.scala:47)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at fs2.internal.Future.$anonfun$flatMap$1(Future.scala:17)
	at fs2.internal.Future.step(Future.scala:53)
	at fs2.internal.Future.listen(Future.scala:30)
	at fs2.internal.Future.$anonfun$listen$3(Future.scala:34)
	at fs2.internal.Future.$anonfun$listen$3$adapted(Future.scala:34)
	at fs2.internal.Trampoline.$anonfun$map$1(Trampoline.scala:10)
	at fs2.internal.Trampoline$.run(Trampoline.scala:31)
	at fs2.internal.Trampoline.run(Trampoline.scala:12)
	at fs2.internal.Trampoline.run$(Trampoline.scala:12)
	at fs2.internal.Trampoline$FlatMap.run(Trampoline.scala:18)
	at fs2.Task$.$anonfun$async$4(Task.scala:247)
	at fs2.Strategy$$anon$7.apply(Strategy.scala:69)
	at fs2.Task$.$anonfun$async$3(Task.scala:247)
	at fs2.Task$.$anonfun$async$3$adapted(Task.scala:247)
	at fs2.Task$.$anonfun$ref$2(Task.scala:314)
	at fs2.Task$.$anonfun$ref$2$adapted(Task.scala:294)
	at fs2.internal.Actor.act(Actor.scala:58)
	at fs2.internal.Actor.lastTry(Actor.scala:69)
	at fs2.internal.Actor.$anonfun$scheduleLastTry$1(Actor.scala:67)
	at fs2.Strategy$$anon$5$$anon$6.run(Strategy.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 relay not permitted

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1917)
	... 36 common frames omitted
```

The smtp settings should be setup properly (they are even displayed on the manual->configuration page, not sure if this is a security issue by the way)
```
sharry{
  smtp {
    host = "<censored>"
    port = 587
    user = "noreply@<censored>"
    password = "<censored>"
    from = "noreply@<censored>"
  }
}
```

The email account is setup and I have another service (ShareLatex) using this successfully with the same settings.

According to my mail service the `550 relay not permitted` occurs when there was no SMTP authentication.

I took a quick look at the source code, but I could not spot any issue. I am not familiar with Scala though.

Any ideas what might go wrong here?

Sharry: Build from 0.3.0 Release tag
OpenJDK 8

**Comment by eikek** [comment]
That sounds strange: the smtp settings on the manual page should only show the default values, but not yours! This would be a very big security issue, of course… I just verified that my own installation shows only the default values. Could you re-check again at yours? 

It indeed seems as if the client doesn't authorize at the smtp server. Could you maybe run the server with the flag `-Dmail.debug=true`? It should get picked up and print javax.mail debug messages to stdout. Maybe it gives more details about the problem. But I think I know the cause: it's a very lazy bug… I invented a non-existing javax.mail property `mail.password` … it doesn't work that way. One has to provide an authenticator (afaik). Don't know what I was thinking back then…  sorry for your inconvenience and thanks for reporting!

**Comment by maxanier** [comment]
Here is the output with the debug settings.
(Even though it says invalid address, the destination and from address are definitively valid)

It seems to be connecting to port 25 even though I set it to 587, but according to my mail provider both should work the same way.

```
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle]}
DEBUG: Providers Listed By Protocol: {imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
2017-10-15T12:07:26.117+0000 DEBUG [sharry-server-ACG-12] sharry.server.email.client [client.scala:44] Createt mime message: Date: Sun, 15 Oct 2017 12:07:26 +0000 (UTC)

From: <cencored>

To:<cencored>

Message-ID: <42046056.0.1508069246115@e6a520bff555>

Subject: Ready to download

MIME-Version: 1.0

Content-Type: text/plain; charset=us-ascii

Content-Transfer-Encoding: 7bit



Hi,

I have pushed some files for you to download. Visit this page:

<cencored>
Cheers,
max
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "smtprelaypool.ispgateway.de", port 25, isSSL false
220 smtprelay04.ispgateway.de ESMTP dfex
DEBUG SMTP: connected to host "smtprelaypool.ispgateway.de", port: 25

EHLO e6a520bff555
250-smtprelay04.ispgateway.de Hello e6a520bff555 [80.209.235.86]
250-SIZE 104857600
MIME
250-PIPELINING
250-AUTH PLAIN LOGIN
KING

TTLS
250 HELP
DEBUG SMTP: Found extension "SIZE", arg "104857600"
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "PIPELINING", arg ""
DEBUG SMTP: Found extension "AUTH", arg "PLAIN LOGIN"
DEBUG SMTP: Found extension "CHUNKING", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "HELP", arg ""
DEBUG SMTP: use8bit false
MAIL FROM:<cencored>
250 OK
RCPT TO:<cencored>
550 relay not permitted
DEBUG SMTP: Invalid Addresses
DEBUG SMTP:   <cencored>
DEBUG SMTP: Sending failed because of invalid destination addresses
RSET

t OK
DEBUG SMTP: MessagingException while sending, THROW: 
javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 550 relay not permitted

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at sharry.server.email.client$.$anonfun$send1$7(client.scala:50)
	at sharry.server.email.client$.$anonfun$send1$7$adapted(client.scala:50)
	at fs2.Task.$anonfun$map$3(Task.scala:47)
	at fs2.util.Attempt$.apply(Attempt.scala:12)
	at fs2.Task.$anonfun$map$2(Task.scala:47)
	at scala.util.Either.flatMap(Either.scala:269)
	at fs2.Task.$anonfun$map$1(Task.scala:47)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at fs2.internal.Future.$anonfun$flatMap$1(Future.scala:17)
	at fs2.internal.Future.step(Future.scala:53)
	at fs2.internal.Future.listen(Future.scala:30)
	at fs2.internal.Future.$anonfun$listen$3(Future.scala:34)
	at fs2.internal.Future.$anonfun$listen$3$adapted(Future.scala:34)
	at fs2.internal.Trampoline.$anonfun$map$1(Trampoline.scala:10)
	at fs2.internal.Trampoline$.run(Trampoline.scala:31)
	at fs2.internal.Trampoline.run(Trampoline.scala:12)
	at fs2.internal.Trampoline.run$(Trampoline.scala:12)
	at fs2.internal.Trampoline$FlatMap.run(Trampoline.scala:18)
	at fs2.Task$.$anonfun$async$4(Task.scala:247)
	at fs2.Strategy$$anon$7.apply(Strategy.scala:69)
	at fs2.Task$.$anonfun$async$3(Task.scala:247)
	at fs2.Task$.$anonfun$async$3$adapted(Task.scala:247)
	at fs2.Task$.$anonfun$ref$2(Task.scala:314)
	at fs2.Task$.$anonfun$ref$2$adapted(Task.scala:294)
	at fs2.internal.Actor.act(Actor.scala:58)
	at fs2.internal.Actor.$anonfun$schedule$1(Actor.scala:54)
	at fs2.Strategy$$anon$5$$anon$6.run(Strategy.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 relay not permitted

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1917)
```

**Comment by maxanier** [comment]
I opened another issue regarding the configuration: #21 

One thing I noticed is that my password is not escaped in the displayed configuration:

```
smtp {
    from="me@me.de"
    host="smtprelaypool.ispgateway.de"
    password=password123
    port="587"
    user="me@me.de"
}
```

**Comment by eikek** [comment]
@maxanier Thanks for reporting these issues! I just pushed fixes for both. Maybe you can try the current master branch?

**Comment by maxanier** [comment]
Works perfectly with the change now :)

Thank you very much for fixing and for creating this cool project! I really like the alias upload function.
