### ISSUE TITLE
Crash with 1.7.0 using docker image

### ISSUE THREAD

**Issue by Diaoul** [eikek/sharry#436]
Thanks for developing and maintaining sharry!

I have this error with 1.7.0 when I try to upload files in a share through an alias.
1.6.0 works fine.

```
2021-05-07 18:55:21,992 [ioapp-compute-0] DEBUG s.b.s.OShare - Result creating share for 'xxxx': Success(RShare(Ident(yyyyyyy),Ident(xxxxxxx),Some(Ident(zzzzzz)),None,30.0 days,10,None,Some(),Timestamp(2021-05-07T18:55:21.953176Z)))
2021-05-07 18:55:22,002 [ioapp-compute-0] INFO o.h.s.m.Logger - HTTP/1.1 POST /api/v2/alias/upload/new
2021-05-07 18:55:22,002 [ioapp-compute-0] INFO o.h.s.m.Logger - HTTP/1.1 200 OK
java.lang.NoClassDefFoundError: javax/activation/MimeType
at bitpeace.Mimetype$.apply(Mimetype.scala:62)
at bitpeace.Mimetype$.<clinit>(Mimetype.scala:48)
at sharry.restserver.routes.tus.SharryFileType$.$anonfun$apply$2(SharryFileType.scala:13)
at scala.Option.flatMap(Option.scala:283)
at sharry.restserver.routes.tus.SharryFileType$.apply(SharryFileType.scala:13)
at sharry.restserver.routes.tus.TusRoutes$TusHeader$.fileInfo(TusRoutes.scala:104)
at sharry.restserver.routes.tus.TusRoutes$$anonfun$apply$1.applyOrElse(TusRoutes.scala:39)
at sharry.restserver.routes.tus.TusRoutes$$anonfun$apply$1.applyOrElse(TusRoutes.scala:33)
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
at org.http4s.HttpRoutes$.$anonfun$of$2(HttpRoutes.scala:79)
at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:114)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:114)
at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:474)
at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:482)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.activation.MimeType
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 35 more
```

**Comment by eikek** [comment]
Oh noes! thanks for reporting. This is one of these annoying dependency issues in the java world. What type of file did you use here and which browser? I tried with several files but could not trigger this.

**Comment by eikek** [comment]
An alternative workaround is to run it with java8 (not java11).

**Comment by Diaoul** [comment]
A few jpg files on Firefox on Arch Linux. Do you use the docker image as
well ?

**Comment by eikek** [comment]
Ah no, I was using java11 but not the docker image. Even more strange.

**Comment by eikek** [comment]
Really strange thing. It is not the cause I had first in mind. The "problem" is with the bitpeace library. It declares an optional dependency on tika-core. But it also uses classes that are added transitively through tika-core. This a bug in bitpeace library, because it uses a class that is not explicitly declared as dependency, even worse that it's an optional dependency. Unfortunately, it doesn't trigger until someone doesn't use tika-core *and* runs on Java11+, because these classes are in the standard jdk in java8 (they are available via a flag in java9/10 and removed in java11).

Now sharry *does* declare a dependency to tika-core (my first suspicion was that this is not the case). And this then also pulls in its transitive dependencies. But for some reason (I have no idea how that happened), these two transitive dependencies are *not* in the zip file! That is why I didn't realize it, because using my dev-setup *they are* in the classpath and in my "production" installation is running on java8.

I can't reproduce this state. When I'm running the package commands again on the v1.7.0 tag, it creates a valid zip file.

So I'm considering now simply a repackaging and publishing a 1.7.1 release…. Going to fix this in the bitpeace library for a later release.

**Comment by Diaoul** [comment]
Thanks !
