### ISSUE TITLE
Unable to run with LC_ALL=C

### ISSUE THREAD

**Issue by vlna** [eikek/sharry#49]
With default `LC_ALL=C` program freezes with

```
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:74)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.addString(TraversableOnce.scala:360)
	at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:356)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1429)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:326)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:325)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
	at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:328)
	at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:328)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1429)
	at sharry.server.App.$anonfun$defaultConfig$2(App.scala:76)
	at scala.collection.immutable.List.map(List.scala:286)
	at sharry.server.App.defaultConfig$lzycompute(App.scala:76)
	at sharry.server.App.defaultConfig(App.scala:72)
	at sharry.server.App.endpoints(App.scala:61)
	at sharry.server.main$.main(main.scala:76)
	at sharry.server.main.main(main.scala)
```

This works
```
LC_ALL=en_US.UTF-8 ./sharry-server-0.6.1.jar.sh 
```

My Java is
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1deb10u1)
OpenJDK Server VM (build 11.0.4+11-post-Debian-1deb10u1, mixed mode)
```

**Comment by eikek** [comment]
Hi @vlna , thank you for reporting! I'll take a look soon.
