### ISSUE TITLE
[Bug] v1.10.0 No database found to handle jdbc...

### ISSUE THREAD

**Issue by shadowking001** [eikek/sharry#766]
Hello,

My watchtower daemon updated Sharry to v1.10.0 some days ago, and since then the container keeps restarting.
I downgraded to v1.9.0 and everything was running smooth, so the last update did break something.
At the first sight on the release logs, I see that you are not using logback anymore, so I removed the argument from the command.
I also see that the config file have evolved a bit since the last time I gave an eye to your documentation, so I have copy pasted the default config file in your documentation (it could be nice to have the same commented config file on the repo btw) and did some tweaking accordingly.

Concerning the logs :

```
2022.04.26 21:55:18:0000 [io-comp...] [INFO ] sharry.restserver.Main.run:52 - 
***>   __ _
***>  \ \| '_ \ / _` | '__| '__| | | |
***>  / _\ |__   __ _ _ __ _ __ _   _
***>  \__/_| |_|\__,_|_|  |_|   \__, |
***>  _\ \ | | | (_| | |  | |  | |_| |
***>                            |___/
***>       v1.10.0 (#11cd780a)
***>  Base-Url: https://sharry.xxx.ovh
***>  Database: jdbc:mariadb://mariadb:3306/sharry
***>  Config:   /opt/sharry.conf
***>  
2022.04.26 21:55:18:0001 [io-comp...] [INFO ] sharry.restserver.Main.run:59 - Alias-Member feature enabled: true
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mariadb://mariadb:3306/sharry
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:55)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:972)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:693)
	at sharry.store.migrate.FlywayMigrate$.makeFlyway(FlywayMigrate.scala:27)
	at sharry.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:16)
	at delay @ sharry.store.migrate.FlywayMigrate$.run(FlywayMigrate.scala:14)
	at map @ sharry.store.doobie.StoreImpl.migrate(StoreImpl.scala:16)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:160)
	at get @ fs2.internal.Scope.openScope(Scope.scala:281)
	at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1060)
	at >>$extension @ fs2.Pull$.fs2$Pull$$go$1(Pull.scala:1218)
	at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:932)
Apr 26, 2022 9:55:21 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2022.04.26 21:55:21:482 io-compute-2 INFO sharry.restserver.Main.run:22
    Using given config file: /opt/sharry.conf
```

It seems like the container can't connect to the database.
Without changing anything, it works in v1.9.0.
I also tried to drop the database and the associated user, no success either.
I also checked that I can connect with the sharry user to the sharry database through command line inside the mariadb container, it works like a charm.

Any idea ? @eikek

**Comment by eikek** [comment]
Hi, oh yes it seems with the upgrade for flyway it requires another library to connect to mariadb databases. It is working for the others, so it's a bit harder to recognize.

**Comment by eikek** [comment]
Hi @shadowking001 The next release will finally fix this. Just read through your comment again, regarding a default config file: there is a commented default config file in the repo [here](https://github.com/eikek/sharry/blob/master/modules/restserver/src/main/resources/reference.conf). It is shown in the doc pages [here](https://eikek.github.io/sharry/doc/configure#default-config), that's why it's not linked from other places.

**Comment by shadowking001** [comment]
Oh nice! thanks for the hard work.
Was sticking to 1.9.0 meanwhile, I will update when released.
Got it for the config file. ;)
