### ISSUE TITLE
SQL Error on initial run using Mariadb

### ISSUE THREAD

**Issue by weboide** [eikek/sharry#812]
I'm attempting to use sharry with Mariadb 10.3.34-MariaDB-0ubuntu0.20.04.1 and I'm hitting the following error.

```sharry        | Jul 03, 2022 11:35:49 AM org.jline.utils.Log logr
sharry        | WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
sharry        | 2022.07.03 11:35:49:286 io-compute-4 INFO sharry.restserver.Main.run:23
sharry        |     Using given config file: /opt/sharry.conf
sharry        | 2022.07.03 11:35:53:0000 [io-comp...] [INFO ] sharry.restserver.Main.run:54 -
sharry        | ***>   __ _
sharry        | ***>  / _\ |__   __ _ _ __ _ __ _   _
sharry        | ***>  \ \| '_ \ / _` | '__| '__| | | |
sharry        | ***>  _\ \ | | | (_| | |  | |  | |_| |
sharry        | ***>  \__/_| |_|\__,_|_|  |_|   \__, |
sharry        | ***>                            |___/
sharry        | ***>       v1.11.0 (#f5ea1a3b)
sharry        | ***>  Base-Url: http://localhost:9090
sharry        | ***>  Database: jdbc:mariadb://cuatro.lan:3306/sharry
sharry        | ***>  Config:   /opt/sharry.conf
sharry        | ***>  FileRepo: DefaultDatabase(true)
sharry        | ***>
sharry        | 2022.07.03 11:35:53:0001 [io-comp...] [INFO ] sharry.restserver.Main.run:55 -
sharry        | Map(Ident(filesystem) -> FileSystem(false,/some/directory), Ident(minio) -> S3(enabled=false, endpoint=http://localhost:9000, bucket=sharry, accessKey=username, secretKey=***), Ident(database) -> DefaultDatabase(true))
sharry        |
sharry        | 2022.07.03 11:35:53:0002 [io-comp...] [INFO ] sharry.restserver.Main.run:62 - Alias-Member feature enabled: true
sharry        | 2022.07.03 11:35:56:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.13 by Redgate
sharry        | 2022.07.03 11:35:56:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
sharry        | 2022.07.03 11:35:56:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter -
sharry        | 2022.07.03 11:35:56:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:mariadb://cuatro.lan/sharry (MariaDB 10.3)
sharry        | 2022.07.03 11:35:56:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Repair of failed migration in Schema History table `sharry`.`flyway_schema_history` not necessary as table doesn't exist.
sharry        | 2022.07.03 11:35:56:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbRepair - Successfully repaired schema history table `sharry`.`flyway_schema_history` (execution time 00:00.104s).
sharry        | 2022.07.03 11:35:56:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.13 by Redgate
sharry        | 2022.07.03 11:35:56:0007 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
sharry        | 2022.07.03 11:35:56:0008 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter -
sharry        | 2022.07.03 11:35:56:0009 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 4 migrations (execution time 00:00.033s)
sharry        | 2022.07.03 11:35:56:0010 [io-comp...] [INFO ] org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table `sharry`.`flyway_schema_history` ...
sharry        | 2022.07.03 11:35:57:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Current version of schema `sharry`: << Empty Schema >>
sharry        | 2022.07.03 11:35:57:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `sharry` to version "1.0.0 - initial"
sharry        | 2022.07.03 11:35:57:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `sharry` to version "1.1.0 - alias member"
sharry        | 2022.07.03 11:35:57:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbMigrate - Migrating schema `sharry` to version "1.2.0 - binary store"
sharry        | 2022.07.03 11:35:57:0004 [io-comp...] [WARN ] org.mariadb.jdbc.message.server.ErrorPacket - Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
sharry        | 2022.07.03 11:35:57:0005 [io-comp...] [ERROR] org.flywaydb.core.internal.command.DbMigrate - Migration of schema `sharry` to version "1.2.0 - binary store" failed! Please restore backups and roll back database and code!
sharry        | org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1.2.0__binary_store.sql failed
sharry        | -----------------------------------------
sharry        | SQL State  : 42000
sharry        | Error Code : 1064
sharry        | Message    : (conn=1805) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
sharry        | Location   : db/migration/mariadb/V1.2.0__binary_store.sql (/opt/file:/opt/sharry-restserver-1.11.0/lib/com.github.eikek.sharry-store-1.11.0.jar!/db/migration/mariadb/V1.2.0__binary_store.sql)
sharry        | Line       : 4
sharry        | Statement  : ALTER TABLE `filemeta`
sharry        | RENAME COLUMN `id` TO `file_id`
sharry        |
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:385)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:275)
sharry        |         at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:274)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:247)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
sharry        |         at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
sharry        |         at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
sharry        |         at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
sharry        |         at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
sharry        |         at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
sharry        |         at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
sharry        |         at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
sharry        |         at sharry.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:18)
sharry        |         at delay @ sharry.store.migrate.FlywayMigrate$.run(FlywayMigrate.scala:14)
sharry        |         at map @ sharry.store.doobie.StoreImpl.migrate(StoreImpl.scala:16)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:161)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at get @ fs2.internal.Scope.openScope(Scope.scala:281)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1057)
sharry        |         at >>$extension @ fs2.Pull$.fs2$Pull$$go$1(Pull.scala:1215)
sharry        |         at get @ fs2.internal.Scope.openScope(Scope.scala:281)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
sharry        |         at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:929)
sharry        |         at get @ fs2.internal.Scope.openScope(Scope.scala:281)
sharry        | Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1.2.0__binary_store.sql failed
sharry        | -----------------------------------------
sharry        | SQL State  : 42000
sharry        | Error Code : 1064
sharry        | Message    : (conn=1805) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
sharry        | Location   : db/migration/mariadb/V1.2.0__binary_store.sql (/opt/file:/opt/sharry-restserver-1.11.0/lib/com.github.eikek.sharry-store-1.11.0.jar!/db/migration/mariadb/V1.2.0__binary_store.sql)
sharry        | Line       : 4
sharry        | Statement  : ALTER TABLE `filemeta`
sharry        | RENAME COLUMN `id` TO `file_id`
sharry        |
sharry        |         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
sharry        |         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
sharry        |         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
sharry        |         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:69)
sharry        |         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:58)
sharry        |         at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
sharry        |         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:57)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:377)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:275)
sharry        |         at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:274)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:247)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
sharry        |         at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
sharry        |         at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
sharry        |         at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
sharry        |         at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
sharry        |         at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
sharry        |         at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
sharry        |         at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
sharry        |         at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
sharry        |         at sharry.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:18)
sharry        |         at cats.effect.IOFiber.runLoop(IOFiber.scala:358)
sharry        |         at cats.effect.IOFiber.execR(IOFiber.scala:1332)
sharry        |         at cats.effect.IOFiber.run(IOFiber.scala:139)
sharry        |         at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
sharry        | Caused by: java.sql.SQLSyntaxErrorException: (conn=1805) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `id` TO `file_id`' at line 2
sharry        |         at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
sharry        |         at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
sharry        |         at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
sharry        |         at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:819)
sharry        |         at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:758)
sharry        |         at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:677)
sharry        |         at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:620)
sharry        |         at org.mariadb.jdbc.Statement.executeInternal(Statement.java:906)
sharry        |         at org.mariadb.jdbc.Statement.execute(Statement.java:1031)
sharry        |         at org.mariadb.jdbc.Statement.execute(Statement.java:441)
sharry        |         at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
sharry        |         at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
sharry        |         at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
sharry        |         ... 25 more
sharry exited with code 1```

**Comment by eikek** [comment]
The problem is that `RENAME COLUMN` came with MariaDB 10.5.2 - You need to upgrade to have the changesets run successfully.

**Comment by weboide** [comment]
I switched to Docker Mariadb version 10.8.3 and it works as intended. Thanks for the tip!
