### ISSUE TITLE
Illegal character [:] in path at index 3 error

### ISSUE THREAD

**Issue by DuckUser201** [eikek/sharry#892]
Java version: 19.0.1 2022-10-18
OS: Windows 10

The entire error: 
```2022.10.18 21:36:24:0000 [io-comp...] [INFO ] sharry.restserver.Main.run:54 -
***>   __ _
***>  / _\ |__   __ _ _ __ _ __ _   _
***>  \ \| '_ \ / _` | '__| '__| | | |
***>  _\ \ | | | (_| | |  | |  | |_| |
***>  \__/_| |_|\__,_|_|  |_|   \__, |
***>                            |___/
***>       v1.11.0 (#f5ea1a3b)
***>  Base-Url: http://localhost:9090
***>  Database: jdbc:h2://C:\Users\User\AppData\Local\Temp\/sharry-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
***>  Config:
***>  FileRepo: DefaultDatabase(true)
***>
2022.10.18 21:36:24:0001 [io-comp...] [INFO ] sharry.restserver.Main.run:55 -
Map(Ident(filesystem) -> FileSystem(false,\some\directory), Ident(minio) -> S3(enabled=false, endpoint=http://localhost:9000, bucket=sharry, accessKey=username, secretKey=***), Ident(database) -> DefaultDatabase(true))

2022.10.18 21:36:24:0002 [io-comp...] [INFO ] sharry.restserver.Main.run:62 - Alias-Member feature enabled: true
2022.10.18 21:36:25:0000 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.13 by Redgate
2022.10.18 21:36:25:0001 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
2022.10.18 21:36:25:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter -
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:h2://C:\Users\User\AppData\Local\Temp\/sharry-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE) for user 'sa': General error: "java.nio.file.InvalidPathException: Illegal character [:] in path at index 3: //C:/Users/User/AppData/Local/Temp//sharry-demo.db" [50000-214]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 50000
Message    : General error: "java.nio.file.InvalidPathException: Illegal character [:] in path at index 3: //C:/Users/User/AppData/Local/Temp//sharry-demo.db" [50000-214]

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147)
        at org.flywaydb.core.Flyway.repair(Flyway.java:326)
        at sharry.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:17)
        at delay @ sharry.store.migrate.FlywayMigrate$.run(FlywayMigrate.scala:14)
        at map @ sharry.store.doobie.StoreImpl.migrate(StoreImpl.scala:16)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:161)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at get @ fs2.internal.Scope.openScope(Scope.scala:281)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1057)
        at >>$extension @ fs2.Pull$.fs2$Pull$$go$1(Pull.scala:1215)
        at get @ fs2.internal.Scope.openScope(Scope.scala:281)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:929)
        at get @ fs2.internal.Scope.openScope(Scope.scala:281)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.nio.file.InvalidPathException: Illegal character [:] in path at index 3: //C:/Users/User/AppData/Local/Temp//sharry-demo.db" [50000-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:212)
        at org.h2.message.DbException.convert(DbException.java:395)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
        at org.h2.Driver.connect(Driver.java:59)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147)
        at org.flywaydb.core.Flyway.repair(Flyway.java:326)
        at sharry.store.migrate.FlywayMigrate$.$anonfun$run$1(FlywayMigrate.scala:17)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:358)
        at cats.effect.IOFiber.execR(IOFiber.scala:1332)
        at cats.effect.IOFiber.run(IOFiber.scala:139)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:523)
Caused by: java.nio.file.InvalidPathException: Illegal character [:] in path at index 3: //C:/Users/User/AppData/Local/Temp//sharry-demo.db
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.h2.store.fs.disk.FilePathDisk.isAbsolute(FilePathDisk.java:321)
        at org.h2.store.fs.FileUtils.isAbsolute(FileUtils.java:144)
        at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:457)
        at org.h2.engine.Engine.openSession(Engine.java:49)
        at org.h2.engine.Engine.openSession(Engine.java:222)
        at org.h2.engine.Engine.createSession(Engine.java:201)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
        ... 13 more```

**Comment by eikek** [comment]
You can use a config file and specify the jdbc url. You can look at this page for pointers: https://eikek.github.io/sharry/doc/configure
