### ISSUE TITLE
MariaDB database migration

### ISSUE THREAD

**Issue by Wunderharke** [eikek/sharry#95]
Hello guys,

there seems to be an issue with initializing the database. One of the files does not exist anymore (`db/migration/common`) and there are some tables with case sensitive names in my setup.
 
` Error servicing request: PATCH /api/v2/alias/upload/XXX/files/tus/XXX from 127.0.0.1
java.sql.SQLSyntaxErrorException: (conn= XXX) Table 'DATABASE.FileChunk' doesn't exist`

I think this happens because [V1.0.0__initial.sql](https://github.com/eikek/sharry/blob/master/modules/store/src/main/resources/db/migration/mariadb/V1.0.0__initial.sql) creates the table `filechunk` however Sharry is checking for `FileChunk` while runtime.

~~This [issue](https://jira.mariadb.org/browse/MCOL-495) might be important.~~ 

I fixed this by adding `lower_case_table_names = 1` underneath the `[mysqld]` section in `/etc/mysql/my.cnf`.

**Comment by eikek** [comment]
Hi @Wunderharke, thank you for reporting! 

Do you mean the warning on startup in the log regarding `db/migration/common`? While this is really confusing, it should be fine actually.

But the bug you describe: I hope that this is already fixed within the bitpeace library [here](https://github.com/eikek/bitpeace/commit/97537737f6a9ff5e1780e9b8ec7d44eede0e8b42). But I first have to try reproduce it in order to be sure. I didn't know about the `lower_case_table_names` option in mariadb. Which version of mariadb are you using? I'm testing with 10.3.20 and I can't find this lowercase setting in my `my.cnf` (but I never changed anything there, just used the defaults of my distro).

**Comment by Wunderharke** [comment]
Hi @eikek,

no problem I like to help, this is the best file-sharing project I've deployed until now. I had a lot more issues with other solutions I've tried.

Regarding your questions: I'm using MriaDB 10.4.12 on Ubuntu Bionic and I used the 1.0.0 .deb package for the installation of sharry.

The option `lower_case_table_names` wasn't present in my configuration eighter, but I added things there before, and tried the fix discribed on [stackexchange](https://dba.stackexchange.com/a/69330) which fixed the problem for me.

If that would help I could revert that change and share the complete stacktrace here. Or are there any logs produced I could upload?

**Comment by eikek** [comment]
Hi @Wunderharke, thank you for your kind words and the offer to help! So… if that would be ok with you, maybe you could try with a new package containing the potential fix? I just build a dev package that can be downloaded [here](http://eknet.org/temp/sharry-1.1.0-SNAPSHOT_all.deb) where the issue should be fixed. If that fixes your problem then I can publish a new release soon. Otherwise I'd need to investigate more. In this case the stacktrace may be helpful.

**Comment by Wunderharke** [comment]
Unfortunately there seems to be a problem with your webserver, I'm just getting a 404. And I would strongly recommend that you always use a Let's Encrypt certificate and https on your web server, especially when downloading executables.
You can just upload the package to [my server](https://send.scrawn.net/app/share/JA7NzmgJhdr-uM7kRQmX56E-YqL9uR9qaP5-W1J6vCKxWmt). I'll disable `lower_case_table_names` afterwards and try the new package.

Meanwhile I found another error:

`WARN  c.z.h.p.PoolBase - HikariPool-1 - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@2e63436e (Connection.setNetworkTimeout cannot be called on a closed connection). Possibly consider using a shorter maxLifetime value.`

I dont't think it's critical however you might consider adding an option to configure `HikariCP.maxLifetime` in the config file.

**Comment by Wunderharke** [comment]
Btw here is the stacktrace:

<details> 
    <summary>stacktrace</summary>
    <p>

```
[ioapp-compute-4] ERROR o.h.s.service-errors - Error servicing request: PATCH /api/v2/sec/upload/*XXX*/files/tus/*XXX* from 127.0.0.1
java.sql.SQLSyntaxErrorException: (conn=38) Table '*DATABASE*.FileChunk' doesn't exist
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:243)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:956)
        at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:112)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
        at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
        at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
        at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
        at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
        at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
        at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
        at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Table '*DATABASE*.FileChunk' doesn't exist
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1599)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1461)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1424)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216)
        ... 28 common frames omitted
```
</details>

**Comment by eikek** [comment]
Sorry for the wrong link, just fixed it. I was pasting the wrong clipboard…. I also uploaded it.

The maxLifetime issue is another thing. Currently there are no database properties configurable. You're right, I should add options for that.

**Comment by Wunderharke** [comment]
Fix seems to work! Thanks for your fast support!

**Comment by eikek** [comment]
That's great to hear! Thank you a lot for your help! I'm going to create a new release soon.
